- name: Run crawler
        run: |
          python crawler.py
          ls -l  # 파일이 실제로 생성되었는지 로그에 출력해서 확인용

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -f exchange.json ]; then
            git add exchange.json
            git commit -m "Update exchange rate" || exit 0
            git push origin main
          else
            echo "Error: exchange.json 파일이 생성되지 않았습니다."
            exit 1
          fi
